CREATE TABLE IF NOT EXISTS materia (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS alumno (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255),
apellido VARCHAR(255),
id_materia BIGINT,
FOREIGN KEY (id_materia) REFERENCES materia(id)
    );
